import { Button, Link } from '@vezham/react/v2'

const Home = () => {
  return (
    <div className="grid grid-cols-6 gap-3 p-5">
      <Button
        showAnchorIcon
        as={Link}
        href="/button"
        variant="flat"
        color="secondary"
        radius="sm">
        Button
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/text"
        variant="flat"
        color="secondary"
        radius="sm">
        Text
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/card"
        variant="flat"
        color="secondary"
        radius="sm">
        Card
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/table"
        variant="flat"
        color="secondary"
        radius="sm">
        Table
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/timeline"
        variant="flat"
        color="secondary"
        radius="sm">
        Timeline
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/footer"
        variant="flat"
        color="secondary"
        radius="sm">
        Footer - WhatsNew
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/footers"
        variant="flat"
        color="secondary"
        radius="sm">
        Footer - HeroUI
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/trending"
        variant="flat"
        color="secondary"
        radius="sm">
        Trending
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/header"
        variant="flat"
        color="secondary"
        radius="sm">
        Header
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/notfound"
        variant="flat"
        color="secondary"
        radius="sm">
        Template - Notfound
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/loading"
        variant="flat"
        color="secondary"
        radius="sm">
        Loading
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/lockscreen"
        variant="flat"
        color="secondary"
        radius="sm">
        LockScreen
      </Button>
    </div>
  )
}

export { Home }
