import { Button, Link } from '@vezham/react/v2'

import { AutoLayout } from '../../layouts/v-auto-layout'

const Home = () => {
  return (
    <AutoLayout direction="horizontal" spacer="md">
      <Button
        showAnchorIcon
        as={Link}
        href="/button"
        variant="flat"
        color="secondary"
        radius="sm">
        Button
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/text"
        variant="flat"
        color="secondary"
        radius="sm">
        Text
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/card"
        variant="flat"
        color="secondary"
        radius="sm">
        Card
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/table"
        variant="flat"
        color="secondary"
        radius="sm">
        Table
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/timeline"
        variant="flat"
        color="secondary"
        radius="sm">
        Timeline
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/footer"
        variant="flat"
        color="secondary"
        radius="sm">
        Footer - WhatsNew
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/footers"
        variant="flat"
        color="secondary"
        radius="sm">
        Footer - HeroUI
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/trending"
        variant="flat"
        color="secondary"
        radius="sm">
        Trending
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/header"
        variant="flat"
        color="secondary"
        radius="sm">
        Header
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/notfound"
        variant="flat"
        color="secondary"
        radius="sm">
        Template - Notfound
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/loading"
        variant="flat"
        color="secondary"
        radius="sm">
        Loading
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/lockscreen"
        variant="flat"
        color="secondary"
        radius="sm">
        LockScreen
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/apps/heropage"
        variant="flat"
        color="secondary"
        radius="sm">
        Containerlayout
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/apps/appbg"
        variant="flat"
        color="secondary"
        radius="sm">
        AppBg
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/apps/appsidebar"
        variant="flat"
        color="secondary"
        radius="sm">
        AppSidebar
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/apps/appsidebarcontainer"
        variant="flat"
        color="secondary"
        radius="sm">
        AppSidebarContainer
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/apps/appsidebarmenu"
        variant="flat"
        color="secondary"
        radius="sm">
        AppSidebarMenu
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/apps/appsidebarpanel"
        variant="flat"
        color="secondary"
        radius="sm">
        AppSidebarPanel
      </Button>
      <Button
        showAnchorIcon
        as={Link}
        href="/land"
        variant="flat"
        color="secondary"
        radius="sm">
        LandingPage
      </Button>
    </AutoLayout>
  )
}

export { Home }
