/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TrendingLazyRouteImport = createFileRoute('/trending')()
const TimelineLazyRouteImport = createFileRoute('/timeline')()
const TextLazyRouteImport = createFileRoute('/text')()
const TableLazyRouteImport = createFileRoute('/table')()
const NotfoundLazyRouteImport = createFileRoute('/notfound')()
const LockscreenLazyRouteImport = createFileRoute('/lockscreen')()
const LoadingLazyRouteImport = createFileRoute('/loading')()
const LandLazyRouteImport = createFileRoute('/land')()
const HeaderLazyRouteImport = createFileRoute('/header')()
const FootersLazyRouteImport = createFileRoute('/footers')()
const FooterLazyRouteImport = createFileRoute('/footer')()
const CardLazyRouteImport = createFileRoute('/card')()
const ButtonLazyRouteImport = createFileRoute('/button')()
const IndexLazyRouteImport = createFileRoute('/')()
const AppsAppsidebarpanelLazyRouteImport = createFileRoute(
  '/apps/appsidebarpanel',
)()
const AppsAppsidebarmenuLazyRouteImport = createFileRoute(
  '/apps/appsidebarmenu',
)()
const AppsAppsidebarcontainerLazyRouteImport = createFileRoute(
  '/apps/appsidebarcontainer',
)()
const AppsAppsidebarLazyRouteImport = createFileRoute('/apps/appsidebar')()
const AppsAppbgLazyRouteImport = createFileRoute('/apps/appbg')()

const TrendingLazyRoute = TrendingLazyRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trending.lazy').then((d) => d.Route))
const TimelineLazyRoute = TimelineLazyRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/timeline.lazy').then((d) => d.Route))
const TextLazyRoute = TextLazyRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/text.lazy').then((d) => d.Route))
const TableLazyRoute = TableLazyRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/table.lazy').then((d) => d.Route))
const NotfoundLazyRoute = NotfoundLazyRouteImport.update({
  id: '/notfound',
  path: '/notfound',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/notfound.lazy').then((d) => d.Route))
const LockscreenLazyRoute = LockscreenLazyRouteImport.update({
  id: '/lockscreen',
  path: '/lockscreen',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/lockscreen.lazy').then((d) => d.Route))
const LoadingLazyRoute = LoadingLazyRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/loading.lazy').then((d) => d.Route))
const LandLazyRoute = LandLazyRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/land.lazy').then((d) => d.Route))
const HeaderLazyRoute = HeaderLazyRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/header.lazy').then((d) => d.Route))
const FootersLazyRoute = FootersLazyRouteImport.update({
  id: '/footers',
  path: '/footers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/footers.lazy').then((d) => d.Route))
const FooterLazyRoute = FooterLazyRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/footer.lazy').then((d) => d.Route))
const CardLazyRoute = CardLazyRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/card.lazy').then((d) => d.Route))
const ButtonLazyRoute = ButtonLazyRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/button.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AppsAppsidebarpanelLazyRoute = AppsAppsidebarpanelLazyRouteImport.update({
  id: '/apps/appsidebarpanel',
  path: '/apps/appsidebarpanel',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/apps/appsidebarpanel.lazy').then((d) => d.Route),
)
const AppsAppsidebarmenuLazyRoute = AppsAppsidebarmenuLazyRouteImport.update({
  id: '/apps/appsidebarmenu',
  path: '/apps/appsidebarmenu',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/apps/appsidebarmenu.lazy').then((d) => d.Route),
)
const AppsAppsidebarcontainerLazyRoute =
  AppsAppsidebarcontainerLazyRouteImport.update({
    id: '/apps/appsidebarcontainer',
    path: '/apps/appsidebarcontainer',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/apps/appsidebarcontainer.lazy').then((d) => d.Route),
  )
const AppsAppsidebarLazyRoute = AppsAppsidebarLazyRouteImport.update({
  id: '/apps/appsidebar',
  path: '/apps/appsidebar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/apps/appsidebar.lazy').then((d) => d.Route),
)
const AppsAppbgLazyRoute = AppsAppbgLazyRouteImport.update({
  id: '/apps/appbg',
  path: '/apps/appbg',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/apps/appbg.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/button': typeof ButtonLazyRoute
  '/card': typeof CardLazyRoute
  '/footer': typeof FooterLazyRoute
  '/footers': typeof FootersLazyRoute
  '/header': typeof HeaderLazyRoute
  '/land': typeof LandLazyRoute
  '/loading': typeof LoadingLazyRoute
  '/lockscreen': typeof LockscreenLazyRoute
  '/notfound': typeof NotfoundLazyRoute
  '/table': typeof TableLazyRoute
  '/text': typeof TextLazyRoute
  '/timeline': typeof TimelineLazyRoute
  '/trending': typeof TrendingLazyRoute
  '/apps/appbg': typeof AppsAppbgLazyRoute
  '/apps/appsidebar': typeof AppsAppsidebarLazyRoute
  '/apps/appsidebarcontainer': typeof AppsAppsidebarcontainerLazyRoute
  '/apps/appsidebarmenu': typeof AppsAppsidebarmenuLazyRoute
  '/apps/appsidebarpanel': typeof AppsAppsidebarpanelLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/button': typeof ButtonLazyRoute
  '/card': typeof CardLazyRoute
  '/footer': typeof FooterLazyRoute
  '/footers': typeof FootersLazyRoute
  '/header': typeof HeaderLazyRoute
  '/land': typeof LandLazyRoute
  '/loading': typeof LoadingLazyRoute
  '/lockscreen': typeof LockscreenLazyRoute
  '/notfound': typeof NotfoundLazyRoute
  '/table': typeof TableLazyRoute
  '/text': typeof TextLazyRoute
  '/timeline': typeof TimelineLazyRoute
  '/trending': typeof TrendingLazyRoute
  '/apps/appbg': typeof AppsAppbgLazyRoute
  '/apps/appsidebar': typeof AppsAppsidebarLazyRoute
  '/apps/appsidebarcontainer': typeof AppsAppsidebarcontainerLazyRoute
  '/apps/appsidebarmenu': typeof AppsAppsidebarmenuLazyRoute
  '/apps/appsidebarpanel': typeof AppsAppsidebarpanelLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/button': typeof ButtonLazyRoute
  '/card': typeof CardLazyRoute
  '/footer': typeof FooterLazyRoute
  '/footers': typeof FootersLazyRoute
  '/header': typeof HeaderLazyRoute
  '/land': typeof LandLazyRoute
  '/loading': typeof LoadingLazyRoute
  '/lockscreen': typeof LockscreenLazyRoute
  '/notfound': typeof NotfoundLazyRoute
  '/table': typeof TableLazyRoute
  '/text': typeof TextLazyRoute
  '/timeline': typeof TimelineLazyRoute
  '/trending': typeof TrendingLazyRoute
  '/apps/appbg': typeof AppsAppbgLazyRoute
  '/apps/appsidebar': typeof AppsAppsidebarLazyRoute
  '/apps/appsidebarcontainer': typeof AppsAppsidebarcontainerLazyRoute
  '/apps/appsidebarmenu': typeof AppsAppsidebarmenuLazyRoute
  '/apps/appsidebarpanel': typeof AppsAppsidebarpanelLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/button'
    | '/card'
    | '/footer'
    | '/footers'
    | '/header'
    | '/land'
    | '/loading'
    | '/lockscreen'
    | '/notfound'
    | '/table'
    | '/text'
    | '/timeline'
    | '/trending'
    | '/apps/appbg'
    | '/apps/appsidebar'
    | '/apps/appsidebarcontainer'
    | '/apps/appsidebarmenu'
    | '/apps/appsidebarpanel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/button'
    | '/card'
    | '/footer'
    | '/footers'
    | '/header'
    | '/land'
    | '/loading'
    | '/lockscreen'
    | '/notfound'
    | '/table'
    | '/text'
    | '/timeline'
    | '/trending'
    | '/apps/appbg'
    | '/apps/appsidebar'
    | '/apps/appsidebarcontainer'
    | '/apps/appsidebarmenu'
    | '/apps/appsidebarpanel'
  id:
    | '__root__'
    | '/'
    | '/button'
    | '/card'
    | '/footer'
    | '/footers'
    | '/header'
    | '/land'
    | '/loading'
    | '/lockscreen'
    | '/notfound'
    | '/table'
    | '/text'
    | '/timeline'
    | '/trending'
    | '/apps/appbg'
    | '/apps/appsidebar'
    | '/apps/appsidebarcontainer'
    | '/apps/appsidebarmenu'
    | '/apps/appsidebarpanel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ButtonLazyRoute: typeof ButtonLazyRoute
  CardLazyRoute: typeof CardLazyRoute
  FooterLazyRoute: typeof FooterLazyRoute
  FootersLazyRoute: typeof FootersLazyRoute
  HeaderLazyRoute: typeof HeaderLazyRoute
  LandLazyRoute: typeof LandLazyRoute
  LoadingLazyRoute: typeof LoadingLazyRoute
  LockscreenLazyRoute: typeof LockscreenLazyRoute
  NotfoundLazyRoute: typeof NotfoundLazyRoute
  TableLazyRoute: typeof TableLazyRoute
  TextLazyRoute: typeof TextLazyRoute
  TimelineLazyRoute: typeof TimelineLazyRoute
  TrendingLazyRoute: typeof TrendingLazyRoute
  AppsAppbgLazyRoute: typeof AppsAppbgLazyRoute
  AppsAppsidebarLazyRoute: typeof AppsAppsidebarLazyRoute
  AppsAppsidebarcontainerLazyRoute: typeof AppsAppsidebarcontainerLazyRoute
  AppsAppsidebarmenuLazyRoute: typeof AppsAppsidebarmenuLazyRoute
  AppsAppsidebarpanelLazyRoute: typeof AppsAppsidebarpanelLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfound': {
      id: '/notfound'
      path: '/notfound'
      fullPath: '/notfound'
      preLoaderRoute: typeof NotfoundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lockscreen': {
      id: '/lockscreen'
      path: '/lockscreen'
      fullPath: '/lockscreen'
      preLoaderRoute: typeof LockscreenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/header': {
      id: '/header'
      path: '/header'
      fullPath: '/header'
      preLoaderRoute: typeof HeaderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footers': {
      id: '/footers'
      path: '/footers'
      fullPath: '/footers'
      preLoaderRoute: typeof FootersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer': {
      id: '/footer'
      path: '/footer'
      fullPath: '/footer'
      preLoaderRoute: typeof FooterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/appsidebarpanel': {
      id: '/apps/appsidebarpanel'
      path: '/apps/appsidebarpanel'
      fullPath: '/apps/appsidebarpanel'
      preLoaderRoute: typeof AppsAppsidebarpanelLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/appsidebarmenu': {
      id: '/apps/appsidebarmenu'
      path: '/apps/appsidebarmenu'
      fullPath: '/apps/appsidebarmenu'
      preLoaderRoute: typeof AppsAppsidebarmenuLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/appsidebarcontainer': {
      id: '/apps/appsidebarcontainer'
      path: '/apps/appsidebarcontainer'
      fullPath: '/apps/appsidebarcontainer'
      preLoaderRoute: typeof AppsAppsidebarcontainerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/appsidebar': {
      id: '/apps/appsidebar'
      path: '/apps/appsidebar'
      fullPath: '/apps/appsidebar'
      preLoaderRoute: typeof AppsAppsidebarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/appbg': {
      id: '/apps/appbg'
      path: '/apps/appbg'
      fullPath: '/apps/appbg'
      preLoaderRoute: typeof AppsAppbgLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ButtonLazyRoute: ButtonLazyRoute,
  CardLazyRoute: CardLazyRoute,
  FooterLazyRoute: FooterLazyRoute,
  FootersLazyRoute: FootersLazyRoute,
  HeaderLazyRoute: HeaderLazyRoute,
  LandLazyRoute: LandLazyRoute,
  LoadingLazyRoute: LoadingLazyRoute,
  LockscreenLazyRoute: LockscreenLazyRoute,
  NotfoundLazyRoute: NotfoundLazyRoute,
  TableLazyRoute: TableLazyRoute,
  TextLazyRoute: TextLazyRoute,
  TimelineLazyRoute: TimelineLazyRoute,
  TrendingLazyRoute: TrendingLazyRoute,
  AppsAppbgLazyRoute: AppsAppbgLazyRoute,
  AppsAppsidebarLazyRoute: AppsAppsidebarLazyRoute,
  AppsAppsidebarcontainerLazyRoute: AppsAppsidebarcontainerLazyRoute,
  AppsAppsidebarmenuLazyRoute: AppsAppsidebarmenuLazyRoute,
  AppsAppsidebarpanelLazyRoute: AppsAppsidebarpanelLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
