export * from './src/lib/useStore/src'
export * from './src/lib/useString/src'
export * from './src/lib/useLogger/src'

export const __DEV__ = process.env.NODE_ENV !== 'production'
export const __TEST__ = process.env.NODE_ENV === 'test'
export const __PRODUCTION__ = process.env.NODE_ENV === 'production'
export const __PREVIEW__ = import.meta.env.V_IS_PREVIEW === 'true'
export const __DEBUG__ = import.meta.env.V_IS_DEBUG === 'true'
export const IS_BETA = import.meta.env.V_IS_BETA === 'true'
export const APP_NAME = import.meta.env.V_APP_NAME || 'vapp'
