# @vx/INFO: @vx/ci
name: playground | bnd

on:
  workflow_dispatch:
  push:
    branches: [timeline, u/*]
    paths:
      - '.github/workflows/playground.yml'
      - 'vx/handbooks/ci.md'
      - 'vx/config/firebase/apps_internals/playground.json'
      - 'vx/config/vercel/__mocks__/mock.json'
      - 'packages/**'
      - 'apps_internals/playground/**'
      - 'apps_internals/playground-e2e/**'
      - 'apps_internals/playground-mock/**'

jobs:
  run_if:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.filter.outputs.all }}
      deploy: ${{ steps.filter.outputs.deploy }}
      mocks: ${{ steps.filter.outputs.mocks }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            all:
              - '.github/workflows/playground.yml'
              - 'vx/handbooks/ci.md'
            deploy:
              - 'vx/config/firebase/apps_internals/playground.json'
              - 'apps_internals/playground/**'
              - 'packages/**'
            mocks:
              - 'vx/config/vercel/__mocks__/mock.json'
              - 'apps_internals/playground-mock/**'

  deploy:
    needs: run_if
    if: ${{ needs.run_if.outputs.all == 'true' || needs.run_if.outputs.deploy == 'true' }}
    name: playground | ${{ github.ref_name }}
    uses: vezham/vx-deployer/.github/workflows/playground.yml@timeline
    secrets: inherit
    with:
      CALLER: ${{ github.ref_name }}

  mocks:
    needs: run_if
    if: ${{ needs.run_if.outputs.mocks == 'true' }}
    name: playground-mock | ${{ github.ref_name }}
    uses: vezham/vx-deployer/.github/workflows/playground-mock.yml@timeline
    secrets: inherit
    with:
      CALLER: ${{ github.ref_name }}
